node {
    deleteDir()

    stage('Checkout') {
        checkout scm
    }

    docker.image('node:16-alpine').inside('-p 3000:3000') {
        
        withEnv(['CI=true']) {
            
            stage('Build') {
                
                sh 'HOME=$(pwd) npm install'
            }
            
            stage('Test') {
               
                sh 'HOME=$(pwd) ./jenkins/scripts/test.sh'
            }
            
            stage('Manual Approval') {
                input message: 'Lanjutkan ke tahap Deploy?'
            }
            
            stage('Deploy') {
                sh 'HOME=$(pwd) ./jenkins/scripts/deliver.sh'
                sleep time: 60, unit: 'SECONDS'
                sh './jenkins/scripts/kill.sh'
            }
            
        }
    }
}